# Generated by Django 5.2.1 on 2025-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(choices=[('charts', 'Dashboard'), ('display_alerts', 'Alerts'), ('cctv_doctor', 'CCTV Doctor'), ('select_stream_view', 'VMS'), ('people_counting', 'People Counting'), ('retail_dashboard', 'Retail Dashboard'), ('create_alert', 'Create Alert'), ('add_site', 'Add Site'), ('select_camera', 'Analytics')], max_length=50)),
                ('display_order', models.PositiveIntegerField()),
                ('custom_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisation_logos/')),
                ('page_configurations', models.ManyToManyField(blank=True, related_name='organisations', to='organisation.pageconfigurationmodel')),
            ],
        ),
    ]
